default_stages: [pre-commit, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: sort-simple-yaml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: ["--branch", "main", "--branch", "master"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.21.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@latest
          - eslint-config-google@latest
          - eslint-plugin-react@latest
          - eslint-plugin-react-hooks@latest
          - "@typescript-eslint/eslint-plugin@latest"
          - "@typescript-eslint/parser@latest"
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: ["--cache", "--no-warn-ignored"]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args: ["--fix"]
