name: Build Website

on:
  pull_request:
    branches:
      - main
      - workflow-research

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Use Node.js 23.7.0
        uses: actions/setup-node@v2
        with:
          node-version: 23.7.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Start server
        run: |
          nohup npm run dev &
          sleep 5

      - name: Test website is running
        run: curl -f http://localhost:3000 || exit 1
